version: '3.7'
services:
  app:
    build: .
    ports:
      - "3001:3000"
      - "3099:3099"
    env_file:
      - .env
    environment:
      CHAINHOOK_NODE_RPC_HOST: "host.docker.internal"
    depends_on:
      - postgres

  postgres:
    image: "postgres:14"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    volumes:
      - hiroAPIpgdata:/var/lib/postgresql/data

volumes:
  hiroAPIpgdata:
