version: '3.7'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
  postgres:
    image: "postgres:14"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
